-- gift_of_life_config.lua
-- Compatibility shim for the original GoL core.
-- Do NOT edit this file. Edit: gift_of_life/config.lua

local function deepMerge(dst, src)
  if type(src) ~= "table" then return dst end
  if type(dst) ~= "table" then dst = {} end
  for k, v in pairs(src) do
    if type(v) == "table" and type(dst[k]) == "table" then
      deepMerge(dst[k], v)
    elseif type(v) == "table" and dst[k] == nil then
      local t = {}
      deepMerge(t, v)
      dst[k] = t
    else
      dst[k] = v
    end
  end
  return dst
end

local function shallowCopy(t)
  local out = {}
  if type(t) == "table" then
    for k, v in pairs(t) do out[k] = v end
  end
  return out
end

local function pathExists(path)
  if type(path) ~= "string" or path == "" then return false end
  if g_resources and type(g_resources.fileExists) == "function" then
    local ok, ex = pcall(g_resources.fileExists, path)
    if ok and ex then return true end
  end
  if g_resources and type(g_resources.readFileContents) == "function" then
    local ok, data = pcall(g_resources.readFileContents, path)
    if ok and type(data) == "string" and #data > 0 then return true end
  end
  if io and io.open then
    local f = io.open(path, "r")
    if f then f:close(); return true end
  end
  return false
end

local function tryLoad()
  local ok, cfg = pcall(dofile, "config.lua")
  if not ok then ok, cfg = pcall(dofile, "gift_of_life/config.lua") end
  if not ok then ok, cfg = pcall(dofile, "modules/gift_of_life/config.lua") end
  if ok and type(cfg) == "table" then return cfg end
  return nil
end

local function tryLoadState()
  -- Try to load persisted UI overlay from the same place we will later save to.
  -- Also expose the chosen VFS path in _G.GoLStatePath for debugging / core use.
  local candidates = {
    "gift_of_life_state.lua",
    "gift_of_life/gift_of_life_state.lua",
    "modules/gift_of_life/gift_of_life_state.lua",
    "/gift_of_life_state.lua",
    "/gift_of_life/gift_of_life_state.lua",
    "/modules/gift_of_life/gift_of_life_state.lua",
  }

  for _, p in ipairs(candidates) do
    if pathExists(p) then
      local ok, st = pcall(dofile, p)
      if ok and type(st) == "table" then
        rawset(_G, "GoLStatePath", p)
        return st
      end
    end
  end

  -- Default (file may not exist yet; it will be created on first save).
  rawset(_G, "GoLStatePath", "gift_of_life/gift_of_life_state.lua")
  return nil
end

local function tryLoadBuiltinProfiles()
  local candidates = {
    "gift_of_life_profiles.lua",
    "gift_of_life/gift_of_life_profiles.lua",
    "modules/gift_of_life/gift_of_life_profiles.lua",
  }
  for _, p in ipairs(candidates) do
    if pathExists(p) then
      local ok, prof = pcall(dofile, p)
      if ok and type(prof) == "table" then
        return prof
      end
    end
  end
  return {}
end

local cfg = tryLoad() or {}
local state = tryLoadState()
local builtinProfiles = tryLoadBuiltinProfiles()

-- Build profiles catalog:
--  1) config.lua profiles (highest priority for "static" config)
--  2) built-in templates (fill missing)
--  3) state.dynamicProfiles (user-edited, persisted; overrides templates)
local profilesAll = shallowCopy(cfg.profiles or {})
for name, p in pairs(builtinProfiles) do
  if profilesAll[name] == nil then profilesAll[name] = p end
end
if state and type(state.dynamicProfiles) == "table" then
  for name, p in pairs(state.dynamicProfiles) do
    profilesAll[name] = p
  end
end

-- Profile selection: UI state can override config activeProfile.
local active = (state and state.activeProfile) or cfg.activeProfile
if type(active) ~= "string" or active == "" then active = "default" end

local out = {}
-- Flatten config for the core (base + active profile)
deepMerge(out, cfg.base or {})
if type(profilesAll[active]) == "table" then
  deepMerge(out, profilesAll[active])
end

-- Expose catalogs for UI/addons (does not affect core logic).
out.base = cfg.base or {}
out.profiles = profilesAll
out.__configProfiles = cfg.profiles or {}

-- Pass addon settings through as well (core will ignore unknown keys).
out.addonsEnabled = cfg.addonsEnabled
out.addons = cfg.addons
out.activeProfile = active

-- UI state overlay (optional) goes LAST.
if state then
  deepMerge(out, state)
end

return out
